name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Pull & restart on server
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            root@${{ secrets.SERVER_HOST }} << 'EOF'
            set -eux
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/market-rest-api:latest
  
              cd ~/market-rest-api
  
              docker-compose up -d
          EOF
