name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy-to-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Pull & restart on server
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            root@${{ secrets.SERVER_HOST }} << 'EOF'
            set -eux
              cd ~/market-rest-api
              git fetch origin main
              git reset --hard origin/main
          
              docker-compose down 
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/market-rest-api:latest
              docker-compose up -d
          EOF
