name: Run Checks

on:
  push:
    branches: [ main ]

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensures full repo history

      # Setup Go environment (using Go 1.21 as before)
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      # Cache Go modules to speed up builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Formatting check using gofmt
      - name: Check formatting with gofmt
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "The following files are not formatted properly:"
            echo "$unformatted"
            exit 1
          fi

      # Pre-build step: force generation of export data for packages
      - name: Pre-build to generate export data
        run: go list -json ./... > /dev/null

      # Install and run golangci-lint using go install
      - name: Run golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          # Ensure the binary is in PATH
          export PATH="$HOME/go/bin:$PATH"
          golangci-lint run

      # Static analysis with go vet
      - name: Run go vet
        run: go vet ./...

      # Install and run gosec using go install
      - name: Run gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          export PATH="$HOME/go/bin:$PATH"
          gosec ./...

      # Run unit tests with coverage for services
      - name: Run unit tests for services
        run: cd internal/services && go test -v -coverprofile=coverage.out
